export const ipc = {
    requestData: () => window.electron.requestData(),
    sendData: (data: any): Promise<any> => window.electron.sendData(data),
    onResponseData: (callback: (event: any, data: any) => void): (() => void) => window.electron.onResponseData(callback),
    saveTAMForm: (data: any) => window.electron.saveTAMForm(data),
    loadNetWorthData: (): Promise<any> => window.electron.loadNetWorthData(),
    saveNetWorthEntry: (entry: any): Promise<any> => window.electron.saveNetWorthEntry(entry),
    deleteNetWorthEntry: (entryId: string): Promise<any> => window.electron.deleteNetWorthEntry(entryId),
    loadRpData: (): Promise<any> => window.electron.loadRpData(),
    saveRpItem: (item: any): Promise<any> => window.electron.saveRpItem(item),
    deleteRpItem: (itemId: string): Promise<any> => window.electron.deleteRpItem(itemId),
    loadBudgetData: (): Promise<any> => window.electron.loadBudgetData(),
    saveBudgetData: (data: any): Promise<any> => window.electron.saveBudgetData(data),
    loadSavingsProjectsData: (): Promise<any> => window.electron.loadSavingsProjectsData(),
    saveSavingsProjectsData: (data: any): Promise<any> => window.electron.saveSavingsProjectsData(data),
    loadEaData: (): Promise<any> => window.electron.loadEaData(),
    saveEaData: (data: any): Promise<any> => window.electron.saveEaData(data),
    saveEaImport: (importData: any): Promise<any> => window.electron.saveEaImport(importData),
    deleteEaImport: (importId: string): Promise<any> => window.electron.deleteEaImport(importId),
    loadRecipesData: (): Promise<any> => window.electron.loadRecipesData(),
    saveRecipe: (recipe: any): Promise<any> => window.electron.saveRecipe(recipe),
    deleteRecipe: (recipeId: string): Promise<any> => window.electron.deleteRecipe(recipeId),
    exportAllData: (): Promise<any> => window.electron.exportAllData(),
    importAllData: (data: any): Promise<void> => window.electron.importAllData(data),
} as const
